name = "FinnishArchetypeBuildingModel"
uuid = "d94f30e3-2b27-4c4f-9fcb-3424fc34d710"
authors = ["Topi Rasku <topi.rasku@vtt.fi>"]
version = "0.1.0"

[deps]
ArchetypeBuildingModel = "83d8b715-256d-42a8-83e0-f336dff6771c"
FinnishBuildingStockData = "e9c5a5b1-9140-4320-a2af-ba1393a35d40"

[compat]
FinnishBuildingStockData = ">= 2.1.4"
ArchetypeBuildingModel = ">= 2.6.2"